### ISSUE TITLE
Shop page--Product Cards

### ISSUE THREAD

**Issue by wcampbell91** [nss-evening-cohort-12/pants-sweat-pants#1]
# User Story
As a user when I click the shop button I should be taken to a page where the products are listed as product-cards.

# AC 
**WHEN** The user visits this page
**THEN** I should see a page showing all of the sweatpants displayed in easy to read product cards
**AND** They should have an image representing the sweatpants
**AND** There should be a Title 
**AND** There should be a description of the sweatpants
**AND** The price should be a price displayed at the bottom
**AND** There should be a button to buy the selected sweatpants

# Dev Notes
* TODO
  Match Style Guide ( #3 )

  Make Product Cards using bootstrap card deck
```html
<div class="card-deck">
  <div class="card" id="pantsCard">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Title</h5>
      <p class="card-text">Description of sweatpants</p>
      <p class="card-text"><small class="text-muted">Price$$$</small></p>
      <button type="button" class="btn btn-primary">BUY</button>
    </div>
  </div>
</div>
```

Create a function for building the cards called buildCards() and use a domString to populate the page

create an array of objects representing each available Sweatpants and loop over it to create domString
```js
sweatPants = [
 {
    id: 1,
    name: 'name', 
    gender: 'gender',
    price: 12, 
    img: ''
  }];
```

use printToDom() function to print the domString to the page

<img width="645" alt="Wireframe-layout" src="https://user-images.githubusercontent.com/62917622/81133400-28d09700-8f17-11ea-8d55-7db5f26a2182.png">

**Comment by michaelclark2** [comment]
What does your data look like? I'm assuming youre going to loop over an array of objects?  if so, put a small description of what they would look like, something like :
```
{
  id: 2,
  name: "pants",
}
```
