### ISSUE TITLE
About page--add storyboard

### ISSUE THREAD

**Issue by petestewart** [nss-evening-cohort-12/pants-sweat-pants#11]
# User Story
As a user, when I land on the About page, I should see a vertical series of pictures and text that I can scroll through from top to bottom to give me a sense of Sweaty's history and their impact on today's culture. 

# AC
**WHEN** I, the user, visit the About page, I should see a large picture having to do with Sweaty's history
**THEN** I should see a heading overlaid on that picture
**AND** I should see an informational paragraph about the founder, origin, journey and current info of Sweaty's underneath that picture
**AND** I should be able to scroll down through a series of pictures with overlaid text showing:
1. original sweatpants designs
2. old factory workers
3. celebrities wearing Sweaty's clothing
4. Sweaty's community involvement

# Dev Notes
* The series of photos and accompanying text should be contained in a javascript array of objects called `aboutFrames`. Objects will be in this format:
```
{
  frameImg: "<url for image here>",
  frameText: "<story that goes with image here>"
}
```

* The photos and text will be printed to the DOM inside of an empty div hard coded in the About page html
* The text for the series of photos should be in light or white text blocks similar to this example https://www.w3schools.com/howto/howto_css_image_text_blocks.asp
* There will be a function called `createFrame()` that gets an image and text from an object inside of an array, and then create a block of HTML that contains the image and overlaid text blocks.
* There will be two CSS classes for the text blocks, named `.text-block-left` and `text-block-right`
* The `createFrame()` function will alternate using the `.text-block-left` and `text-block-right` classes using logic that depends on whether the index number for each element is odd or even.
* There will be a function called `createStoryboard()` that loops through the elements of the `aboutFrames` array and creates a `domString` variable containing HTML that will be printed to the div.

WIREFRAME:
![About page wireframe](https://user-images.githubusercontent.com/62906411/81132500-3e908d00-8f14-11ea-9fa1-7c1f5957f1cf.png)

**Comment by michaelclark2** [comment]
I would put a sample of an object that you plan on putting into the `aboutFrames` array, something like: 
```
{
  imgUrl: "<url here>",
  someNumber: 4,
}
```

**Comment by petestewart** [comment]
Good idea. Dev notes are updated with a sample object inserted.

**Comment by petestewart** [comment]
I combined the proposed functions into one function called `buildAboutFrames()` as it became apparent that was going to be more efficient.

Also, I used the same grey color we've been using for the site buttons (`#6c757d`) as the backdrop for the text boxes instead of white since that stood out from the images more effectively.
