### ISSUE TITLE
Nav Bar - Add to Total

### ISSUE THREAD

**Issue by MLogan1998** [nss-evening-cohort-12/pants-sweat-pants#12]

**Comment by MLogan1998** [comment]
# User Story
As a user, when I click 'Add To Cart' on any item, the total price of my cart should update on the nav bar. 

# AC
**WHEN** The user adds an item to the cart
**THEN** The total price of their cart should update on the nav bar.
**AND**  When the user navigates to any page the price should remain on the nav bar.

# Dev Notes
*  The dollar amount is currently hard-coded into the nav bar.
* Use addToToal function to add the price of item to total when user clicks add to cart.
![addtocartwireframe](https://user-images.githubusercontent.com/62910269/81238802-9a1c5280-8fc8-11ea-98a4-eb3cda249e13.jpg)

**Comment by petestewart** [comment]
Also added a pop-up to display contents of the shopping cart with a button on the nav bar to display it.

(Only functions on the Shop page currently)
