### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by MLogan1998** [nss-evening-cohort-12/pants-sweat-pants#2]

**Comment by MLogan1998** [comment]
# User Story
As a user, when I visit any page on the site, I should see a navigation bar at the top of the page with links to the 'Shop,' 'About,' and 'Reviews' pages. I should also see a total dollar amount for items added to my cart.

# AC
**WHEN** The user first visits any page on the site
**THEN**  The user should see a navigation bar
**AND**  When the user hovers over a link the text should change colors
**AND**  When the user clicks the link it should navigate to the corresponding page.

# Dev Notes
* Navigation Bar will use google font 'Jost'. 
* Navigation link default color will be 'Cool Grey' #8592AC.
* Navigation link on hover will be 'Copper' #B17B33
* Cart total will be hard-coded in for now. addToTotal function is on a separate ticket.
![navbarwireframe](https://user-images.githubusercontent.com/62910269/81132182-22d8b700-8f13-11ea-9e10-00bc849bb5bf.jpg)

**Comment by luketlancaster** [comment]
I'd split out the "total dollar amount"/cart functionality to it's own card. You can have a landing spot for it done on this card, but just hardcode a number in there for now
