### ISSUE TITLE
About page--basic layout

### ISSUE THREAD

**Issue by petestewart** [nss-evening-cohort-12/pants-sweat-pants#4]
# User Story
As a user, when I land on the About page, I should see a picture and below it a text box that gives me a brief sense of Sweaty's history and their impact on today's culture. 

# AC
**WHEN** I, the user, visit the About page, I should see a large picture having to do with Sweaty's history
**THEN** I should see a heading overlaid on that picture
**AND** I should see an informational paragraph about the founder, origin, journey and current info of Sweaty's underneath that picture

# Dev Notes
* Hard code the top picture and text, and use the bootstrap component "Fluid jumbotron" https://getbootstrap.com/docs/4.0/components/jumbotron/
* Hard code the informational paragraph below the jumbotron, and create a simple white or light box that slightly overlays on the bottom of the jumbotron by using a negative top margin

WIREFRAME:
![image](https://user-images.githubusercontent.com/62906411/81237674-d4d0bb80-8fc5-11ea-9c57-1a07942a880e.png)

**Comment by petestewart72** [comment]
![About page wireframe](https://user-images.githubusercontent.com/62906411/81132413-fa04f180-8f13-11ea-8dfc-cf9bfac8b533.png)
(These don't have to be the final pictures)

**Comment by luketlancaster** [comment]
This _could_ be broken up into two cards 🤔. One is the creation of the page itself and all the hard-coded things, another is the JS side/data creation/printing to dom. Might not need to, but it would give you more git experience, which isn't the worst thing

**Comment by petestewart** [comment]
Sounds good!
