### ISSUE TITLE
Shop page--Layout

### ISSUE THREAD

**Issue by wcampbell91** [nss-evening-cohort-12/pants-sweat-pants#6]
# User Story
As a user when I visit the shop sweatpants page I should see a header with a navbar at the top with an image underneath as well as sort buttons and product cards to represent each sweatpant

# AC 
**WHEN** The user visits this page
**THEN** I should see a page header with the title of the page.
**AND** Underneath that, a navbar with links to the other pages on the site.
**AND** An image
**AND** Buttons for sorting the pants into different categories: Men's, Women's, Kids
**AND** Product Cards for each sweatpant

# Dev Notes
* TODO
  Match Style Guide ( #3 )

  Create an h1 header with the title of the page

  add navbar from #2 

  add responsive image using boot strap
    `<img src="..." class="img-fluid" alt="Responsive image">`

  add sort buttons using bootstrap buttons
    `<button type="button" class="btn btn-primary">sortButton</button>`

  add product cards using bootstrap card decks and use the buildCards() function from #1 to create. 
    ```<div class="card" id="pantsCard">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Title</h5>
      <p class="card-text">Description of sweatpants</p>
      <p class="card-text"><small class="text-muted">Price$$$</small></p>
      <button type="button" class="btn btn-primary">BUY</button>
    </div>
 
populate the page using the printToDom function in #1. 

<img width="645" alt="Wireframe-layout" src="https://user-images.githubusercontent.com/62917622/81133149-61bc3c00-8f16-11ea-8983-2a148e60b44c.png">

**Comment by luketlancaster** [comment]
looks like the add product cards bit on this is similar to what you have in #1. Is there code from there you plan on reusing?

**Comment by wcampbell91** [comment]
@luketlancaster Yeah! I'll update it shortly
