### ISSUE TITLE
Review page- Bootstrap Carousel

### ISSUE THREAD

**Issue by nathanieltylerowens** [nss-evening-cohort-12/pants-sweat-pants#8]
# User Story
As a user, when I first visit the review page I will see a Reviews title followed by a Nav Bar. Under the Nav Bar will be a Carousel of images with static review snippets on each slide. Followed with a grid of static reviews then a review form just above the footer.  Carousel will have built in arrows as well as auto cycle for the images.  

# AC
WHEN the user first visits the site
THEN I should see a carousel of images and review quotes(4-5)
AND there should be a grid of reviews underneath the carousel
AND there should be a form with name and review form with a submit button underneath

# Dev Notes
TODO

HTML
Use Bootstrap carousel with captions follwing style guide
```html
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="..." alt="First slide">
      <div class="carousel-caption d-none d-md-block">
         <h5>Review caption</h5>
      </div>
    </div>
  </div>
<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```

![carousel highlight](https://user-images.githubusercontent.com/62910227/81239100-786f9b00-8fc9-11ea-8c84-74c341f9224f.jpg)

**Comment by nathanieltylerowens** [comment]
# User Story
As a user, when I first visit the site, I should see a landing page that is just absurdly long. Like, way too long.
# AC
**WHEN** the user first visits the site
**THEN** I should see a landing page
**AND** there should be a mission statement
**AND** there should be a cookie of the day
**AND** there should be a covid statement
**AND** there should be a special/coupon
# Dev Notes
* TODO

**Comment by michaelclark2** [comment]
How do you cycle the carousel?   Put some notes in the dev notes how you think the carousel is going to cycle through the images.

Are the reviews cycling in the carousel as well? or are they static and don't change with the carousel.   if so, we need clarification on how youre going to do that
